name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  workflow_dispatch:
jobs:
  check-test-message:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Echo Message"
        run: |
          echo "TEST TEST TEST"
  call-first:
    uses: ./.github/workflows/first.yaml
  call-second:
    uses: ./.github/workflows/second.yaml
  call-third:
    needs: [call-first, call-second]
    uses: ./.github/workflows/third.yaml
